# Generated by Django 2.2 on 2020-07-02 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_level',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
